version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: contract_manager_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Project
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - contract-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: contract_manager_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    expose:
      - "80"
    depends_on:
      - db
    networks:
      - contract-network
      - nginx-proxy

  app:
    build: .
    container_name: contract_manager_app
    restart: always
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=Project
      - NODE_ENV=production
    networks:
      - contract-network
      - nginx-proxy
    volumes:
      - ./uploads:/usr/src/app/uploads
      - /usr/src/app/node_modules

  nginx:
    image: nginx:alpine
    container_name: contract_manager_nginx
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./uploads:/usr/src/app/

volumes:
  mysql_data:

networks:
  contract-network:
    name: contract_manager_network
    driver: bridge
  nginx-proxy:
    external: true
