export enum NotificationType {
  CONTRACT_PENDING_APPROVAL = "PENDING_APPROVAL",
  CONTRACT_APPROVED = "APPROVED",
  CONTRACT_REJECTED = "REJECTED",
  CONTRACT_SIGNED = "SIGNED",
  CONTRACT_READY_TO_SIGN = "READY_TO_SIGN",
}
