name: Deploy to VPS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          DEPLOY_PATH: "/root/projects/manager-be"
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          export SSHPASS=$VPS_PASSWORD
          SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=30"

          # Function to execute SSH commands with error handling
          ssh_exec() {
            if ! sshpass -e ssh $SSH_OPTS $VPS_USERNAME@$VPS_HOST "$1"; then
              echo "Error executing: $1"
              exit 1
            fi
          }

          # Deploy to VPS
          ssh_exec "cd $DEPLOY_PATH && \
            # Stop all services
            docker-compose down && \
            
            # Clean untracked files and dist directory
            git clean -fd && \
            rm -rf dist/ && \
            
            # Fetch and reset to match remote
            git fetch origin staging && \
            git reset --hard origin/staging && \
            
            # Remove all images and volumes (optional, uncomment if needed)
            # docker system prune -af && \
            # docker volume prune -f && \
            
            # Rebuild and start services
            docker-compose build --no-cache app && \
            docker-compose up -d && \
            
            # Show status and logs
            docker-compose ps"
