name: Deploy to VPS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          DEPLOY_PATH: "/root/projects/manager-be"
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          export SSHPASS=$VPS_PASSWORD
          SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=30"

          # Function to execute SSH commands with error handling
          ssh_exec() {
            if ! sshpass -e ssh $SSH_OPTS $VPS_USERNAME@$VPS_HOST "$1"; then
              echo "Error executing: $1"
              exit 1
            fi
          }

          # Backup important files and handle uncommitted changes
          ssh_exec "cd $DEPLOY_PATH && \
            # Backup certbot and any other important directories
            if [ -d certbot ]; then cp -r certbot certbot_backup; fi && \
            if [ -f nginx.conf ]; then cp nginx.conf nginx.conf.backup; fi && \
            
            # Stash any local changes
            git stash save 'Backup of local changes' || true && \
            
            # Fetch and reset to match remote
            git fetch origin staging && \
            git reset --hard origin/staging && \
            
            # Restore backups
            if [ -d certbot_backup ]; then \
              rm -rf certbot && \
              mv certbot_backup certbot; \
            fi && \
            if [ -f nginx.conf.backup ]; then \
              mv nginx.conf.backup nginx.conf; \
            fi && \
            
            # Rebuild and restart containers
            docker-compose down && \
            docker-compose build --no-cache && \
            docker-compose up -d && \
            docker-compose ps"
