name: Deploy to VPS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          DEPLOY_PATH: "/root/projects/manager-be"
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          export SSHPASS=$VPS_PASSWORD
          SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=30"

          # Function to execute SSH commands with error handling
          ssh_exec() {
            if ! sshpass -e ssh $SSH_OPTS $VPS_USERNAME@$VPS_HOST "$1"; then
              echo "Error executing: $1"
              exit 1
            fi
          }

          # Deploy to VPS
          ssh_exec "cd $DEPLOY_PATH && \
            # Backup important files
            if [ -d certbot ]; then cp -r certbot certbot_backup; fi && \
            
            # Stop all services
            docker-compose down && \
            
            # Clean untracked files
            git clean -fd && \
            
            # Fetch and reset to match remote
            git fetch origin staging && \
            git reset --hard origin/staging && \
            
            # Make init-letsencrypt.sh executable
            chmod +x init-letsencrypt.sh && \
            
            # Restore certbot backup
            if [ -d certbot_backup ]; then \
              rm -rf certbot && \
              mv certbot_backup certbot; \
            fi && \
            
            # Start with HTTP only first
            sed -i 's/listen 443 ssl/#listen 443 ssl/g' nginx.conf && \
            sed -i 's/listen \[::\]:443 ssl/#listen [::]:443 ssl/g' nginx.conf && \
            sed -i 's/return 301 https/return 307 http/g' nginx.conf && \
            sed -i 's/ssl_certificate/#ssl_certificate/g' nginx.conf && \
            sed -i 's/ssl_certificate_key/#ssl_certificate_key/g' nginx.conf && \
            sed -i 's/ssl_dhparam/#ssl_dhparam/g' nginx.conf && \
            
            # Generate DH params if not exists
            if [ ! -f certbot/conf/ssl-dhparams.pem ]; then
              openssl dhparam -out certbot/conf/ssl-dhparams.pem 2048
            fi && \
            
            # Start nginx only first
            docker-compose up -d nginx && \
            
            # Wait for nginx to start
            sleep 10 && \
            
            # Run certbot
            ./init-letsencrypt.sh && \
            
            # Restore original nginx config
            git checkout nginx.conf && \
            
            # Start all services
            docker-compose up -d && \
            
            # Show status
            docker-compose ps"
