name: Deploy to VPS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          DEPLOY_PATH: "/root/projects/manager-be"
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        run: |
          export SSHPASS=$VPS_PASSWORD
          SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=30"

          # Function to execute SSH commands with error handling
          ssh_exec() {
            if ! sshpass -e ssh $SSH_OPTS $VPS_USERNAME@$VPS_HOST "$1"; then
              echo "Error executing: $1"
              exit 1
            fi
          }

          # Deploy to VPS
          ssh_exec "cd $DEPLOY_PATH && \
            # Backup important files
            if [ -d certbot ]; then cp -r certbot certbot_backup; fi && \
            
            # Clean untracked files and reset working directory
            git clean -fd && \
            git checkout -- . && \
            
            # Fetch and reset to match remote
            git fetch origin staging && \
            git reset --hard origin/staging && \
            
            # Restore certbot backup
            if [ -d certbot_backup ]; then \
              rm -rf certbot && \
              mv certbot_backup certbot; \
            fi && \
            
            # Verify nginx config before restart
            docker-compose up -d nginx && \
            docker-compose exec -T nginx nginx -t && \
            
            # If nginx config is valid, restart all services
            docker-compose down && \
            docker-compose build --no-cache && \
            docker-compose up -d && \
            docker-compose ps"
