name: Deploy to Production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: prod
          fetch-depth: 0

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS
        env:
          DEPLOY_PATH: "/root/projects/manager-be"
          VPS_HOST: ${{ secrets.VPS_PROD_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_PROD_USERNAME }}
          VPS_PASSWORD: ${{ secrets.VPS_PROD_PASSWORD }}
        run: |
          export SSHPASS=$VPS_PASSWORD
          SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=30"

          # Function to execute SSH commands with error handling
          ssh_exec() {
            if ! sshpass -e ssh $SSH_OPTS $VPS_USERNAME@$VPS_HOST "$1"; then
              echo "Error executing: $1"
              exit 1
            fi
          }

          # Deploy to VPS with detailed steps
          ssh_exec "cd $DEPLOY_PATH && \
            echo 'Stopping containers...' && \
            docker-compose down && \
            
            echo 'Cleaning workspace...' && \
            git clean -fd && \
            git checkout prod && \
            git fetch origin prod && \
            git reset --hard origin/prod && \
            
            echo 'Removing old containers and images...' && \
            docker-compose rm -f && \
            docker rmi \$(docker images -q 'manager-be_app') || true && \
            
            echo 'Building and starting all services...' && \
            docker-compose up -d --build && \
            
            echo 'Waiting for services to be ready...' && \
            sleep 15 && \
            
            echo 'Verifying deployment...' && \
            docker-compose ps && \
            docker-compose logs app --tail=50"
